import math

import numpy as np
import pandas as pd
from prophet import Prophet
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

from db import get_connection


FORECAST_DESCRIPTION = (
    "Forecasts generated by Linear Regression and Prophet are evaluated using MAE and RMSE. "
    "The approach with the lowest prediction error is selected."
)


def get_forecast_summary():
    conn = get_connection()

    query = """
        SELECT
            p.product_id,
            p.product_code,
            p.product_name,
            p.selling_price,
            DATE_TRUNC('month', s.sale_date) AS sale_month,
            SUM(sd.quantity) AS total_quantity,
            SUM(sd.subtotal) AS total_revenue
        FROM sale_detail sd
        JOIN sale s ON sd.sale_id = s.sale_id
        JOIN product p ON sd.product_id = p.product_id
        GROUP BY
            p.product_id,
            p.product_code,
            p.product_name,
            p.selling_price,
            DATE_TRUNC('month', s.sale_date)
        ORDER BY p.product_id, sale_month;
    """

    try:
        df = pd.read_sql_query(query, conn)
    finally:
        conn.close()

    if df.empty:
        return {
            "message": "No sales data available for forecasting.",
            "description": FORECAST_DESCRIPTION,
            "forecast_period": None,
            "predicted_top_seller": None,
            "product_code": None,
            "total_forecast_units": 0,
            "best_model": None,
            "predicted_revenue": 0,
            "forecasts": [],
        }

    df["sale_month"] = pd.to_datetime(df["sale_month"])
    df["month_index"] = df["sale_month"].dt.year * 12 + df["sale_month"].dt.month

    forecasts = []

    for product_id, group in df.groupby("product_id"):
        group = group.sort_values("sale_month").reset_index(drop=True)

        product_code = group.iloc[0]["product_code"]
        product_name = group.iloc[0]["product_name"]
        selling_price = float(group.iloc[0]["selling_price"] or 0)

        total_quantity = int(group["total_quantity"].sum())
        total_revenue = float(group["total_revenue"].sum())

        monthly_sales = []
        for _, row in group.iterrows():
            monthly_sales.append({
                "month": row["sale_month"].strftime("%Y-%m"),
                "quantity": int(row["total_quantity"]),
                "revenue": float(row["total_revenue"]),
            })

        latest_month = group["sale_month"].max()
        next_month = latest_month + pd.DateOffset(months=1)
        next_month_index = int(next_month.year * 12 + next_month.month)

        model_results = []

        if len(group) < 4:
            forecast_quantity = int(group.iloc[-1]["total_quantity"])

            forecasts.append({
                "product_id": int(product_id),
                "product_code": product_code,
                "product_name": product_name,
                "selling_price": selling_price,
                "total_quantity": total_quantity,
                "total_revenue": total_revenue,
                "forecast_month": next_month.strftime("%Y-%m"),
                "forecast_quantity": forecast_quantity,
                "predicted_revenue": round(forecast_quantity * selling_price, 2),
                "trend": "Not enough data",
                "selected_model": "Fallback: Last Month Sales",
                "mae": None,
                "rmse": None,
                "model_comparison": [],
                "monthly_sales": monthly_sales,
            })
            continue

        split_index = int(len(group) * 0.8)
        train = group.iloc[:split_index]
        test = group.iloc[split_index:]

        if len(test) == 0:
            test = group.iloc[-1:]
            train = group.iloc[:-1]

        try:
            x_train = train[["month_index"]].values
            y_train = train["total_quantity"].values

            x_test = test[["month_index"]].values
            y_test = test["total_quantity"].values

            lr_model = LinearRegression()
            lr_model.fit(x_train, y_train)

            lr_test_pred = lr_model.predict(x_test)
            lr_test_pred = np.maximum(lr_test_pred, 0)

            lr_mae = mean_absolute_error(y_test, lr_test_pred)
            lr_rmse = math.sqrt(mean_squared_error(y_test, lr_test_pred))

            lr_future_pred = lr_model.predict([[next_month_index]])[0]
            lr_future_pred = max(0, round(float(lr_future_pred)))

            model_results.append({
                "model": "Linear Regression",
                "mae": round(float(lr_mae), 2),
                "rmse": round(float(lr_rmse), 2),
                "forecast_quantity": int(lr_future_pred),
            })
        except Exception as e:
            print("Linear Regression error:", e)

        try:
            prophet_train = train[["sale_month", "total_quantity"]].rename(
                columns={
                    "sale_month": "ds",
                    "total_quantity": "y",
                }
            )

            prophet_test = test[["sale_month", "total_quantity"]].rename(
                columns={
                    "sale_month": "ds",
                    "total_quantity": "y",
                }
            )

            prophet_model = Prophet(
                yearly_seasonality=False,
                weekly_seasonality=False,
                daily_seasonality=False,
            )

            prophet_model.fit(prophet_train)

            prophet_forecast_test = prophet_model.predict(prophet_test[["ds"]])
            prophet_test_pred = prophet_forecast_test["yhat"].values
            prophet_test_pred = np.maximum(prophet_test_pred, 0)

            y_test = prophet_test["y"].values

            prophet_mae = mean_absolute_error(y_test, prophet_test_pred)
            prophet_rmse = math.sqrt(mean_squared_error(y_test, prophet_test_pred))

            future_df = pd.DataFrame({
                "ds": [next_month],
            })

            prophet_future = prophet_model.predict(future_df)
            prophet_future_pred = prophet_future["yhat"].iloc[0]
            prophet_future_pred = max(0, round(float(prophet_future_pred)))

            model_results.append({
                "model": "Prophet",
                "mae": round(float(prophet_mae), 2),
                "rmse": round(float(prophet_rmse), 2),
                "forecast_quantity": int(prophet_future_pred),
            })
        except Exception as e:
            print("Prophet error:", e)

        if model_results:
            best_model = min(model_results, key=lambda item: item["rmse"])

            forecast_quantity = best_model["forecast_quantity"]
            selected_model = best_model["model"]
            mae = best_model["mae"]
            rmse = best_model["rmse"]
        else:
            forecast_quantity = int(group.iloc[-1]["total_quantity"])
            selected_model = "Fallback: Last Month Sales"
            mae = None
            rmse = None

        first_qty = float(group.iloc[0]["total_quantity"])
        last_qty = float(group.iloc[-1]["total_quantity"])

        if last_qty > first_qty:
            trend = "Increasing"
        elif last_qty < first_qty:
            trend = "Declining"
        else:
            trend = "Stable"

        forecasts.append({
            "product_id": int(product_id),
            "product_code": product_code,
            "product_name": product_name,
            "selling_price": selling_price,
            "total_quantity": total_quantity,
            "total_revenue": total_revenue,
            "forecast_month": next_month.strftime("%Y-%m"),
            "forecast_quantity": int(forecast_quantity),
            "predicted_revenue": round(int(forecast_quantity) * selling_price, 2),
            "trend": trend,
            "selected_model": selected_model,
            "mae": mae,
            "rmse": rmse,
            "model_comparison": model_results,
            "monthly_sales": monthly_sales,
        })

    forecasts = sorted(
        forecasts,
        key=lambda item: item["forecast_quantity"],
        reverse=True,
    )

    top_forecast = forecasts[0] if forecasts else None

    return {
        "message": "Forecast generated successfully.",
        "description": FORECAST_DESCRIPTION,
        "forecast_period": top_forecast.get("forecast_month") if top_forecast else None,
        "predicted_top_seller": top_forecast.get("product_name") if top_forecast else None,
        "product_code": top_forecast.get("product_code") if top_forecast else None,
        "total_forecast_units": top_forecast.get("forecast_quantity") if top_forecast else 0,
        "best_model": top_forecast.get("selected_model") if top_forecast else None,
        "predicted_revenue": top_forecast.get("predicted_revenue") if top_forecast else 0,
        "forecasts": forecasts,
    }
