import math

import numpy as np
import pandas as pd
from prophet import Prophet
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

from db import get_connection


FORECAST_DESCRIPTION = (
    "Forecasts generated by Linear Regression and Prophet are evaluated using MAE and RMSE. "
    "The approach with the lowest RMSE is selected, with MAE as the tie-breaker."
)


def _to_records(df, columns):
    return [
        {
            column: (
                row[column].strftime("%Y-%m")
                if column == "sale_month" and hasattr(row[column], "strftime")
                else int(row[column])
                if column == "total_quantity_sold"
                else float(row[column])
                if isinstance(row[column], (np.floating, float))
                else row[column]
            )
            for column in columns
        }
        for _, row in df[columns].iterrows()
    ]


def _build_selection_reason(selected, candidates):
    if not selected:
        return "No trained model was available, so the fallback forecast was used."

    other_models = [item for item in candidates if item["model"] != selected["model"]]
    if not other_models:
        return f"{selected['model']} was the only trained model available."

    other = other_models[0]

    if selected["rmse"] < other["rmse"]:
        return (
            f"{selected['model']} selected because RMSE {selected['rmse']} "
            f"is lower than {other['model']} RMSE {other['rmse']}."
        )

    if selected["rmse"] == other["rmse"] and selected["mae"] < other["mae"]:
        return (
            f"{selected['model']} selected because RMSE tied at {selected['rmse']} "
            f"and MAE {selected['mae']} is lower than {other['model']} MAE {other['mae']}."
        )

    return "Linear Regression selected because RMSE and MAE tied."


def _select_best_model(model_results):
    return min(
        model_results,
        key=lambda item: (
            item["rmse"],
            item["mae"],
            0 if item["model"] == "Linear Regression" else 1,
        ),
    )


def _print_product_debug(
    product_name,
    monthly_sales_data,
    train_data,
    test_data,
    linear_raw_prediction,
    prophet_raw_prediction,
    linear_mae,
    linear_rmse,
    prophet_mae,
    prophet_rmse,
    selected_method,
    final_forecast_quantity,
):
    print("================================")
    print("Product:", product_name)
    print("Monthly Sales Data:", monthly_sales_data)
    print("Train Data:", train_data)
    print("Test Data:", test_data)
    print("Linear Regression Raw Prediction:", linear_raw_prediction)
    print("Prophet Raw Prediction:", prophet_raw_prediction)
    print("Linear MAE:", linear_mae)
    print("Linear RMSE:", linear_rmse)
    print("Prophet MAE:", prophet_mae)
    print("Prophet RMSE:", prophet_rmse)
    print("Selected Forecast Method:", selected_method)
    print("Final Forecast Quantity:", final_forecast_quantity)
    print("================================")


def get_forecast_summary(debug=False):
    conn = get_connection()

    query = """
        SELECT
            p.product_id,
            p.product_code,
            p.product_name,
            p.selling_price,
            DATE_TRUNC('month', s.sale_date) AS sale_month,
            SUM(sd.quantity) AS total_quantity_sold,
            SUM(sd.subtotal) AS total_sales_revenue
        FROM sale_detail sd
        JOIN sale s ON sd.sale_id = s.sale_id
        JOIN product p ON sd.product_id = p.product_id
        GROUP BY
            p.product_id,
            p.product_code,
            p.product_name,
            p.selling_price,
            DATE_TRUNC('month', s.sale_date)
        ORDER BY p.product_id, sale_month;
    """

    try:
        df = pd.read_sql_query(query, conn)
    finally:
        conn.close()

    if df.empty:
        return {
            "message": "No sales data available for forecasting.",
            "description": FORECAST_DESCRIPTION,
            "forecast_period": None,
            "predicted_top_seller": None,
            "product_code": None,
            "total_forecast_units": 0,
            "best_model": None,
            "predicted_revenue": 0,
            "forecasts": [],
            **({"debug": []} if debug else {}),
        }

    df["sale_month"] = pd.to_datetime(df["sale_month"])
    df["month_index"] = df["sale_month"].dt.year * 12 + df["sale_month"].dt.month

    forecasts = []
    debug_info = []

    for product_id, group in df.groupby("product_id"):
        group = group.sort_values("sale_month").reset_index(drop=True)

        product_code = group.iloc[0]["product_code"]
        product_name = group.iloc[0]["product_name"]
        selling_price = float(group.iloc[0]["selling_price"] or 0)

        total_quantity_sold = int(group["total_quantity_sold"].sum())
        total_sales_revenue = float(group["total_sales_revenue"].sum())

        monthly_sales = []
        for _, row in group.iterrows():
            monthly_sales.append({
                "month": row["sale_month"].strftime("%Y-%m"),
                "quantity": int(row["total_quantity_sold"]),
                "revenue": float(row["total_sales_revenue"]),
            })

        latest_month = group["sale_month"].max()
        next_month = latest_month + pd.DateOffset(months=1)
        next_month_index = int(next_month.year * 12 + next_month.month)

        model_results = []
        monthly_sales_data = [
            {"month": item["month"], "quantity": item["quantity"]}
            for item in monthly_sales
        ]
        train_data = []
        test_data = []
        linear_raw_prediction = None
        prophet_raw_prediction = None
        linear_mae = None
        linear_rmse = None
        prophet_mae = None
        prophet_rmse = None
        selection_reason = "Fallback used because fewer than 4 monthly sales records are available."

        if len(group) < 4:
            forecast_quantity = int(group.iloc[-1]["total_quantity_sold"])
            selected_model = "Fallback: Last Month Sales"

            _print_product_debug(
                product_name,
                monthly_sales_data,
                train_data,
                test_data,
                linear_raw_prediction,
                prophet_raw_prediction,
                linear_mae,
                linear_rmse,
                prophet_mae,
                prophet_rmse,
                selected_model,
                forecast_quantity,
            )

            if debug:
                debug_info.append({
                    "product_name": product_name,
                    "monthly_sales_series": monthly_sales_data,
                    "linear_regression_prediction": linear_raw_prediction,
                    "prophet_prediction": prophet_raw_prediction,
                    "linear_mae": linear_mae,
                    "linear_rmse": linear_rmse,
                    "prophet_mae": prophet_mae,
                    "prophet_rmse": prophet_rmse,
                    "selected_method": selected_model,
                    "final_forecast_quantity": forecast_quantity,
                    "selection_reason": selection_reason,
                })

            forecasts.append({
                "product_id": int(product_id),
                "product_code": product_code,
                "product_name": product_name,
                "selling_price": selling_price,
                "total_quantity": total_quantity_sold,
                "total_revenue": total_sales_revenue,
                "total_quantity_sold": total_quantity_sold,
                "total_sales_revenue": total_sales_revenue,
                "forecast_month": next_month.strftime("%Y-%m"),
                "forecast_quantity": forecast_quantity,
                "predicted_revenue": round(forecast_quantity * selling_price, 2),
                "trend": "Not enough data",
                "selected_model": selected_model,
                "mae": None,
                "rmse": None,
                "model_comparison": [],
                "monthly_sales": monthly_sales,
                "selection_reason": selection_reason,
            })
            continue

        split_index = int(len(group) * 0.8)
        train = group.iloc[:split_index]
        test = group.iloc[split_index:]

        if len(test) == 0:
            test = group.iloc[-1:]
            train = group.iloc[:-1]

        train_data = _to_records(train, ["sale_month", "total_quantity_sold"])
        test_data = _to_records(test, ["sale_month", "total_quantity_sold"])

        try:
            x_train = train[["month_index"]].values
            y_train = train["total_quantity_sold"].values

            x_test = test[["month_index"]].values
            y_test = test["total_quantity_sold"].values

            lr_model = LinearRegression()
            lr_model.fit(x_train, y_train)

            lr_test_pred = lr_model.predict(x_test)

            lr_mae = mean_absolute_error(y_test, lr_test_pred)
            lr_rmse = math.sqrt(mean_squared_error(y_test, lr_test_pred))
            linear_mae = round(float(lr_mae), 2)
            linear_rmse = round(float(lr_rmse), 2)

            linear_raw_prediction = float(lr_model.predict([[next_month_index]])[0])
            lr_future_pred = round(linear_raw_prediction)
            if linear_raw_prediction < 0:
                print(
                    f"Negative Linear Regression prediction for {product_name}:",
                    linear_raw_prediction,
                )
            lr_future_quantity = max(0, lr_future_pred)

            model_results.append({
                "model": "Linear Regression",
                "mae": linear_mae,
                "rmse": linear_rmse,
                "raw_prediction": linear_raw_prediction,
                "forecast_quantity": int(lr_future_quantity),
            })
        except Exception as e:
            print("Linear Regression error:", e)

        try:
            prophet_train = train[["sale_month", "total_quantity_sold"]].rename(
                columns={
                    "sale_month": "ds",
                    "total_quantity_sold": "y",
                }
            )

            prophet_test = test[["sale_month", "total_quantity_sold"]].rename(
                columns={
                    "sale_month": "ds",
                    "total_quantity_sold": "y",
                }
            )

            prophet_model = Prophet(
                yearly_seasonality=False,
                weekly_seasonality=False,
                daily_seasonality=False,
            )

            prophet_model.fit(prophet_train)

            prophet_forecast_test = prophet_model.predict(prophet_test[["ds"]])
            prophet_test_pred = prophet_forecast_test["yhat"].values

            y_test = prophet_test["y"].values

            prophet_mae = mean_absolute_error(y_test, prophet_test_pred)
            prophet_rmse = math.sqrt(mean_squared_error(y_test, prophet_test_pred))
            prophet_mae = round(float(prophet_mae), 2)
            prophet_rmse = round(float(prophet_rmse), 2)

            future_df = pd.DataFrame({
                "ds": [next_month],
            })

            prophet_future = prophet_model.predict(future_df)
            prophet_raw_prediction = float(prophet_future["yhat"].iloc[0])
            prophet_future_pred = round(prophet_raw_prediction)
            if prophet_raw_prediction < 0:
                print(
                    f"Negative Prophet prediction for {product_name}:",
                    prophet_raw_prediction,
                )
            prophet_future_quantity = max(0, prophet_future_pred)

            model_results.append({
                "model": "Prophet",
                "mae": prophet_mae,
                "rmse": prophet_rmse,
                "raw_prediction": prophet_raw_prediction,
                "forecast_quantity": int(prophet_future_quantity),
            })
        except Exception as e:
            print("Prophet error:", e)

        if model_results:
            best_model = _select_best_model(model_results)

            forecast_quantity = best_model["forecast_quantity"]
            selected_model = best_model["model"]
            mae = best_model["mae"]
            rmse = best_model["rmse"]
            selection_reason = _build_selection_reason(best_model, model_results)
        else:
            forecast_quantity = int(group.iloc[-1]["total_quantity_sold"])
            selected_model = "Fallback: Last Month Sales"
            mae = None
            rmse = None
            selection_reason = "No trained model was available, so the fallback forecast was used."

        _print_product_debug(
            product_name,
            monthly_sales_data,
            train_data,
            test_data,
            linear_raw_prediction,
            prophet_raw_prediction,
            linear_mae,
            linear_rmse,
            prophet_mae,
            prophet_rmse,
            selected_model,
            forecast_quantity,
        )

        if debug:
            debug_info.append({
                "product_name": product_name,
                "monthly_sales_series": monthly_sales_data,
                "linear_regression_prediction": linear_raw_prediction,
                "prophet_prediction": prophet_raw_prediction,
                "linear_mae": linear_mae,
                "linear_rmse": linear_rmse,
                "prophet_mae": prophet_mae,
                "prophet_rmse": prophet_rmse,
                "selected_method": selected_model,
                "final_forecast_quantity": int(forecast_quantity),
                "selection_reason": selection_reason,
            })

        first_qty = float(group.iloc[0]["total_quantity_sold"])
        last_qty = float(group.iloc[-1]["total_quantity_sold"])

        if last_qty > first_qty:
            trend = "Increasing"
        elif last_qty < first_qty:
            trend = "Declining"
        else:
            trend = "Stable"

        forecasts.append({
            "product_id": int(product_id),
            "product_code": product_code,
            "product_name": product_name,
            "selling_price": selling_price,
            "total_quantity": total_quantity_sold,
            "total_revenue": total_sales_revenue,
            "total_quantity_sold": total_quantity_sold,
            "total_sales_revenue": total_sales_revenue,
            "forecast_month": next_month.strftime("%Y-%m"),
            "forecast_quantity": int(forecast_quantity),
            "predicted_revenue": round(int(forecast_quantity) * selling_price, 2),
            "trend": trend,
            "selected_model": selected_model,
            "mae": mae,
            "rmse": rmse,
            "model_comparison": model_results,
            "monthly_sales": monthly_sales,
            "selection_reason": selection_reason,
        })

    forecasts = sorted(
        forecasts,
        key=lambda item: item["forecast_quantity"],
        reverse=True,
    )

    top_forecast = forecasts[0] if forecasts else None

    response = {
        "message": "Forecast generated successfully.",
        "description": FORECAST_DESCRIPTION,
        "forecast_period": top_forecast.get("forecast_month") if top_forecast else None,
        "predicted_top_seller": top_forecast.get("product_name") if top_forecast else None,
        "product_code": top_forecast.get("product_code") if top_forecast else None,
        "total_forecast_units": top_forecast.get("forecast_quantity") if top_forecast else 0,
        "best_model": top_forecast.get("selected_model") if top_forecast else None,
        "predicted_revenue": top_forecast.get("predicted_revenue") if top_forecast else 0,
        "forecasts": forecasts,
    }

    if debug:
        response["debug"] = sorted(
            debug_info,
            key=lambda item: item["product_name"],
        )

    return response
