import DashboardLayout from "../layouts/DashboardLayout";
import React, { useEffect, useId, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
    BarChart3,
    Bot,
    ChevronRight,
    FileDown,
    FileSpreadsheet,
    Info,
    Package,
    Printer,
    TrendingUp,
    X,
} from "lucide-react";
import { motion } from "framer-motion";
import { downloadPDF } from "../utils/downloadPDF";
import { formatCurrency } from "../utils/formatCurrency";

const API_BASE = "http://localhost:5000";

export default function AdminReportsForecasting() {
    const navigate = useNavigate();

    const [user, setUser] = useState(null);
    const [forecastData, setForecastData] = useState([]);
    const [forecastModel, setForecastModel] = useState("");
    const [products, setProducts] = useState([]);
    const [inventory, setInventory] = useState([]);
    const [loading, setLoading] = useState(true);

    const [showSettings, setShowSettings] = useState(false);
    const [showForecastDrawer, setShowForecastDrawer] = useState(false);
    const [isPdfGenerating, setIsPdfGenerating] = useState(false);

    useEffect(() => {
        const savedUser =
            JSON.parse(sessionStorage.getItem("user")) ||
            JSON.parse(sessionStorage.getItem("user"));

        if (!savedUser) {
            navigate("/");
            return;
        }

        setUser(savedUser);
        fetchData();
    }, [navigate]);

    const fetchData = async () => {
        try {
            setLoading(true);

            const [forecastRes, productRes, inventoryRes] = await Promise.all([
                fetch(`${API_BASE}/admin/forecast/products`),
                fetch(`${API_BASE}/admin/products`),
                fetch(`${API_BASE}/admin/inventory`),
            ]);

            const forecastJson = await forecastRes.json();
            const productData = await productRes.json();
            const inventoryData = await inventoryRes.json();

            setForecastData(Array.isArray(forecastJson.forecasts) ? forecastJson.forecasts : []);
            setForecastModel(
                forecastJson.description ||
                "Forecasts generated by Linear Regression and Prophet are evaluated using MAE and RMSE"
            );
            setProducts(Array.isArray(productData) ? productData : []);
            setInventory(Array.isArray(inventoryData) ? inventoryData : []);
        } catch (error) {
            console.error(error);
            alert("Failed to load forecasting data. Please check backend API.");
        } finally {
            setLoading(false);
        }
    };

    const forecastResults = useMemo(() => {
        return sortForecastResultsByDemand(forecastData);
    }, [forecastData]);

    const topForecastProduct = forecastResults[0] || null;

    const totalForecastQuantity = useMemo(() => {
        return forecastResults.reduce(
            (sum, item) => sum + Number(item.forecast_quantity || 0),
            0
        );
    }, [forecastResults]);

    const totalHistoricalQuantity = useMemo(() => {
        return forecastResults.reduce(
            (sum, item) => sum + getTotalQuantitySold(item),
            0
        );
    }, [forecastResults]);

    const averageMae = useMemo(() => {
        const values = forecastResults
            .map((item) => Number(item.mae))
            .filter((value) => !Number.isNaN(value));

        if (values.length === 0) return null;
        return values.reduce((sum, value) => sum + value, 0) / values.length;
    }, [forecastResults]);

    const averageRmse = useMemo(() => {
        const values = forecastResults
            .map((item) => Number(item.rmse))
            .filter((value) => !Number.isNaN(value));

        if (values.length === 0) return null;
        return values.reduce((sum, value) => sum + value, 0) / values.length;
    }, [forecastResults]);

    const forecastGrowth = useMemo(() => {
        return calculateForecastGrowth(totalForecastQuantity, totalHistoricalQuantity);
    }, [totalForecastQuantity, totalHistoricalQuantity]);

    const confidenceScore = useMemo(() => {
        return calculateForecastConfidence(averageRmse, totalForecastQuantity);
    }, [averageRmse, totalForecastQuantity]);

    const selectedModelSummary = topForecastProduct?.selected_model || "No Data";

    const generatedDate = useMemo(() => new Date(), []);
    const generatedDateTime = useMemo(() => {
        return generatedDate.toLocaleString();
    }, [generatedDate]);
    const generatedDateForFile = useMemo(() => {
        const year = generatedDate.getFullYear();
        const month = String(generatedDate.getMonth() + 1).padStart(2, "0");
        const day = String(generatedDate.getDate()).padStart(2, "0");
        return `${year}${month}${day}`;
    }, [generatedDate]);

    const slowMovingProducts = useMemo(() => {
        return [...forecastResults]
            .filter((item) => getTotalQuantitySold(item) <= 5)
            .sort((a, b) => getTotalQuantitySold(a) - getTotalQuantitySold(b))
            .slice(0, 5);
    }, [forecastResults]);

    const historicalTopSellingProducts = useMemo(() => {
        return [...forecastResults]
            .sort(compareHistoricalSalesPerformance)
            .slice(0, 5);
    }, [forecastResults]);

    const lowStockItems = useMemo(() => {
        return inventory.filter((item) => {
            const product = products.find(
                (p) => Number(p.product_id) === Number(item.product_id)
            );
            const reorderLevel = Number(product?.reorder_level || 10);
            return Number(item.quantity_in_stock || 0) <= reorderLevel;
        });
    }, [inventory, products]);

    const handlePrintReport = () => {
        window.print();
    };

    const handleExportExcel = () => {
        const workbookXml = buildForecastWorkbookXml({
            forecastResults,
            products,
            inventory,
            generatedDateTime,
            totalForecastQuantity,
            forecastGrowth,
            confidenceScore,
        });
        const blob = new Blob([workbookXml], {
            type: "application/vnd.ms-excel;charset=utf-8;",
        });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");

        link.href = url;
        link.download = `RetailPulse_Forecast_Report_${generatedDateForFile}.xls`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    const handleDownloadPdf = async () => {
        try {
            setIsPdfGenerating(true);
            document.body.classList.add("exporting-report");
            await new Promise((resolve) => setTimeout(resolve, 100));
            await downloadPDF({
                elementId: "forecast-report-content",
                fileName: `RetailPulse_Forecast_Report_${generatedDateForFile}.pdf`,
            });
        } finally {
            document.body.classList.remove("exporting-report");
            setIsPdfGenerating(false);
        }
    };

    return (
        <>
            <style>
                {`
                    .exporting-report .no-print {
                        display: none !important;
                    }

                    @media print {
                        @page {
                            size: A4;
                            margin: 14mm;
                        }

                        html,
                        body,
                        #root {
                            height: auto !important;
                            overflow: visible !important;
                            background: #ffffff !important;
                        }

                        body * {
                            visibility: hidden !important;
                        }

                        #forecast-report-content,
                        #forecast-report-content * {
                            visibility: visible !important;
                        }

                        #forecast-report-content {
                            position: absolute !important;
                            left: 0 !important;
                            top: 0 !important;
                            width: 100% !important;
                            background: #ffffff !important;
                            color: #07102f !important;
                        }

                        .no-print {
                            display: none !important;
                        }

                        #forecast-report-content section,
                        #forecast-report-content .report-panel {
                            break-inside: avoid;
                            page-break-inside: avoid;
                        }

                        #forecast-report-content .shadow-sm,
                        #forecast-report-content .shadow-xl {
                            box-shadow: none !important;
                        }

                        #forecast-report-content .bg-gradient-to-br {
                            background: #07102f !important;
                            color: #ffffff !important;
                            print-color-adjust: exact;
                            -webkit-print-color-adjust: exact;
                        }
                    }
                `}
            </style>

            <DashboardLayout
                user={user}
                title="Reports & Forecasting"
                subtitle="Analyze product sales trends and estimate next-month demand."
                modelText={forecastModel}
                onRefresh={fetchData}
                onOpenSettings={() => setShowSettings(true)}
            >

                {loading ? (
                    <div className="grid min-h-[70vh] place-items-center text-[#6f85a3]">
                        <div className="text-center">
                            <TrendingUp size={42} className="mx-auto mb-3" />
                            <p className="font-semibold">Loading forecasting data...</p>
                        </div>
                    </div>
                ) : (
                    <>
                        <div className="mb-6 flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between">
                            <div>
                                <p className="text-sm font-semibold text-[#6f85a3]">
                                    Generated: {generatedDateTime}
                                </p>
                            </div>

                            <div className="no-print">
                                <p className="mb-2 text-xs font-bold uppercase tracking-widest text-[#6f85a3]">
                                    Export & Reporting Tools
                                </p>
                                <div className="flex flex-wrap gap-3">
                                    <ReportActionButton
                                        icon={Printer}
                                        label="Print Report"
                                        onClick={handlePrintReport}
                                    />
                                    <ReportActionButton
                                        icon={FileSpreadsheet}
                                        label="Export Excel"
                                        onClick={handleExportExcel}
                                    />
                                    <ReportActionButton
                                        icon={FileDown}
                                        label={isPdfGenerating ? "Generating PDF..." : "Download PDF"}
                                        onClick={handleDownloadPdf}
                                        disabled={isPdfGenerating}
                                        primary
                                    />
                                </div>
                            </div>
                        </div>

                        <div id="forecast-report-content">
                            <div className="mb-6 rounded-2xl bg-white p-6 shadow-sm">
                                <p className="text-xs font-bold uppercase tracking-widest text-[#1e4db7]">
                                    RetailPulse
                                </p>
                                <h2 className="mt-2 text-2xl font-extrabold text-[#07102f]">
                                    Forecast Report
                                </h2>
                                <p className="mt-1 text-sm text-[#6f85a3]">
                                    Analyze product sales trends and estimate next-month demand.
                                </p>
                                <p className="mt-2 text-xs font-bold text-[#17325c]">
                                    Generated: {generatedDateTime}
                                </p>
                            </div>

                            <section className="mb-6 rounded-3xl bg-gradient-to-br from-[#07102f] via-[#0c2f73] to-[#1e4db7] p-7 text-white shadow-xl">
                                <div className="grid grid-cols-1 gap-6 xl:grid-cols-[1.4fr_0.6fr]">
                                    <div>
                                        <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-white/15 px-4 py-2 text-xs font-bold uppercase tracking-widest">
                                            <Bot size={15} />
                                            Predictive Forecast Engine
                                        </div>

                                        <h2 className="text-3xl font-extrabold">
                                            Next-Month Sales Prediction
                                        </h2>

                                        <p className="mt-3 max-w-3xl text-sm leading-6 text-blue-100">
                                            The system evaluates forecasts generated by Linear Regression and Prophet using MAE and RMSE metrics,
                                            then automatically selects the approach with the lowest prediction error to generate the final forecast.
                                        </p>

                                        <div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-3">
                                            <HeroMetric
                                                label="Predicted Top Seller"
                                                value={topForecastProduct?.product_name || "No Data"}
                                            />

                                            <HeroMetric
                                                label="Total Forecast Units"
                                                value={totalForecastQuantity}
                                            />

                                            <HeroMetric
                                                label="Top Seller Forecast Method"
                                                value={selectedModelSummary}
                                            />
                                        </div>
                                    </div>

                                    <div className="rounded-3xl bg-white/12 p-5 backdrop-blur">
                                        <p className="text-sm font-bold text-blue-100">
                                            Forecast Confidence
                                        </p>

                                        <h3 className="mt-3 text-5xl font-extrabold">
                                            {confidenceScore !== null ? `${confidenceScore.toFixed(1)}%` : "-"}
                                        </h3>

                                        <p className="mt-3 text-sm text-blue-100">
                                            Based on average RMSE compared with total forecast quantity.
                                        </p>

                                        <div className="mt-5 h-3 overflow-hidden rounded-full bg-white/20">
                                            <div
                                                className="h-full rounded-full bg-white"
                                                style={{
                                                    width: `${confidenceScore !== null ? confidenceScore : 0}%`,
                                                }}
                                            />
                                        </div>

                                        <div className="mt-5 rounded-2xl bg-white/10 p-4">
                                            <p className="text-xs font-bold uppercase tracking-widest text-blue-100">
                                                Forecast Growth
                                            </p>

                                            <p
                                                className={`mt-2 text-2xl font-extrabold ${forecastGrowth >= 0 ? "text-emerald-200" : "text-red-200"
                                                    }`}
                                            >
                                                {forecastGrowth.toFixed(1)}%
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </section>

                            <section className="mb-6 grid grid-cols-1 gap-5 xl:grid-cols-6">
                                <SummaryCard
                                    title="Forecast Top Seller"
                                    value={topForecastProduct?.product_name || "No Data"}
                                    icon={Package}
                                    color="text-[#1e4db7]"
                                />

                                <SummaryCard
                                    title="Forecast Quantity"
                                    value={topForecastProduct?.forecast_quantity || 0}
                                    icon={TrendingUp}
                                    color="text-green-600"
                                />

                                <SummaryCard
                                    title="Top Seller Forecast Method"
                                    value={topForecastProduct?.selected_model || "No Data"}
                                    icon={Bot}
                                    color="text-purple-600"
                                />

                                <SummaryCard
                                    title="Average MAE"
                                    value={averageMae !== null ? averageMae.toFixed(2) : "-"}
                                    icon={BarChart3}
                                    color="text-orange-600"
                                />

                                <SummaryCard
                                    title="Average RMSE"
                                    value={averageRmse !== null ? averageRmse.toFixed(2) : "-"}
                                    icon={BarChart3}
                                    color="text-red-600"
                                />

                                <SummaryCard
                                    title="Low Stock Items"
                                    value={lowStockItems.length}
                                    icon={BarChart3}
                                    color="text-red-600"
                                />
                            </section>

                            <section className="mb-6 grid grid-cols-1 gap-6 xl:grid-cols-[1.2fr_0.8fr]">
                                <div className="rounded-2xl bg-white p-6 shadow-sm">
                                    <div className="flex items-center justify-between gap-4">
                                        <div>
                                            <div className="flex items-center gap-2">
                                                <h2 className="text-xl font-extrabold text-[#07102f]">
                                                    Forecasting Approach Performance
                                                </h2>
                                                <span
                                                    className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-[#eef6fb] text-[#1e4db7]"
                                                    title="Linear Regression and Prophet are forecasting approaches used to estimate future sales demand."
                                                    aria-label="Linear Regression and Prophet are forecasting approaches used to estimate future sales demand."
                                                >
                                                    <Info size={14} />
                                                </span>
                                            </div>
                                            <p className="mt-1 text-sm text-[#6f85a3]">
                                                Prediction performance comparison between forecasting approaches using MAE and RMSE evaluation metrics.
                                            </p>
                                        </div>

                                        <button
                                            onClick={() => setShowForecastDrawer(true)}
                                            className="no-print flex items-center gap-2 rounded-2xl bg-[#0c2f73] px-4 py-3 text-sm font-extrabold text-white shadow hover:bg-[#103986]"
                                        >
                                            View Details
                                            <ChevronRight size={18} />
                                        </button>
                                    </div>

                                    <div className="mt-6 space-y-4">
                                        {forecastResults.slice(0, 8).map((item) => {
                                            const maxForecast = Math.max(
                                                ...forecastResults.map((p) => Number(p.forecast_quantity || 0)),
                                                1
                                            );
                                            const width = `${(Number(item.forecast_quantity || 0) / maxForecast) * 100}%`;

                                            return (
                                                <div key={item.product_id}>
                                                    <div className="mb-2 flex items-center justify-between text-sm">
                                                        <div className="font-extrabold text-[#17325c]">
                                                            {item.product_name}
                                                        </div>
                                                        <div className="font-bold text-[#6f85a3]">
                                                            {item.forecast_quantity} units
                                                        </div>
                                                    </div>

                                                    <div className="h-3 overflow-hidden rounded-full bg-[#eef6fb]">
                                                        <div
                                                            className="h-full rounded-full bg-[#1e4db7]"
                                                            style={{ width }}
                                                        />
                                                    </div>

                                                    <div className="mt-1 flex items-center justify-between text-xs font-semibold text-[#6f85a3]">
                                                        <span>
                                                            {item.selected_model
                                                                ? `Selected Forecasting Approach: ${item.selected_model}`
                                                                : "Selected Forecasting Approach: -"}
                                                        </span>
                                                        <span>RMSE: {item.rmse ?? "-"}</span>
                                                    </div>
                                                </div>
                                            );
                                        })}

                                        {forecastResults.length === 0 && (
                                            <EmptyBox text="No forecast data available. Check sales history and backend API." />
                                        )}
                                    </div>
                                </div>

                                <div className="rounded-2xl bg-white p-6 shadow-sm">
                                    <h2 className="text-xl font-extrabold text-[#07102f]">
                                        Forecast Assistant Summary
                                    </h2>

                                    <p className="mt-1 text-sm text-[#6f85a3]">
                                        Business insight generated from forecast and stock data.
                                    </p>

                                    <div className="mt-5 rounded-2xl bg-[#f8fcff] p-5">
                                        <p className="font-bold text-[#17325c]">
                                            {topForecastProduct
                                                ? `${topForecastProduct.product_name} is expected to have the highest demand next month.`
                                                : "More sales data is needed before a forecast can be generated."}
                                        </p>

                                        <p className="mt-3 text-sm leading-6 text-[#6f85a3]">
                                            Top Seller Forecast Method:{" "}
                                            <span className="font-bold text-[#1e4db7]">
                                                {topForecastProduct?.selected_model || "-"}
                                            </span>
                                            . The final forecast is generated by the approach with the lower RMSE.
                                        </p>
                                    </div>

                                    <div className="mt-5 grid grid-cols-2 gap-3">
                                        <MiniMetric
                                            label="Average MAE"
                                            value={averageMae !== null ? averageMae.toFixed(2) : "-"}
                                        />
                                        <MiniMetric
                                            label="Average RMSE"
                                            value={averageRmse !== null ? averageRmse.toFixed(2) : "-"}
                                        />
                                    </div>

                                </div>
                            </section>

                            <section className="mb-6 grid grid-cols-1 gap-6 xl:grid-cols-2">
                                <ForecastTable
                                    title="Historical Sales Performance"
                                    data={historicalTopSellingProducts}
                                    metric="historicalRevenue"
                                />
                                <ForecastTable
                                    title="Slow Moving Products"
                                    data={slowMovingProducts}
                                    tooltip="Products with low sales activity during the last 30 days. These products may require promotional actions, stock redistribution, or reduced future purchasing to avoid excess inventory."
                                />
                            </section>
                        </div>
                    </>
                )}
            </DashboardLayout>

            <button
                onClick={() => setShowForecastDrawer(true)}
                className="no-print fixed right-0 top-1/2 z-40 flex h-24 w-11 -translate-y-1/2 items-center justify-center rounded-l-2xl bg-[#0c2f73] text-white shadow-2xl hover:bg-[#103986]"
                title="Open forecast details"
            >
                <ChevronRight size={28} />
            </button>

            {showForecastDrawer && (
                <div className="fixed inset-0 z-50 bg-black/30">
                    <motion.div
                        initial={{ x: "100%" }}
                        animate={{ x: 0 }}
                        exit={{ x: "100%" }}
                        transition={{ duration: 0.3 }}
                        className="absolute right-0 top-0 h-full w-[760px] max-w-[92vw] overflow-y-auto bg-white shadow-2xl"
                    >
                        <div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-7 py-5">
                            <div>
                                <h2 className="text-2xl font-extrabold text-[#07102f]">
                                    Forecast Breakdown
                                </h2>
                                <p className="mt-1 text-sm font-semibold text-[#6f85a3]">
                                    Forecasting approach performance comparison, MAE/RMSE, and product-level forecast details.
                                </p>
                            </div>

                            <button
                                onClick={() => setShowForecastDrawer(false)}
                                className="grid h-10 w-10 place-items-center rounded-full bg-[#eef6fb] text-[#17325c]"
                            >
                                <X size={22} />
                            </button>
                        </div>

                        <div className="space-y-6 p-7">
                            <section className="rounded-3xl bg-[#07102f] p-6 text-white">
                                <p className="text-xs font-bold uppercase tracking-widest text-blue-100">
                                    Selected Forecast Result
                                </p>

                                <h3 className="mt-3 text-3xl font-extrabold">
                                    {topForecastProduct?.product_name || "No Data"}
                                </h3>

                                <div className="mt-5 grid grid-cols-2 gap-4">
                                    <DrawerMetric
                                        label="Forecast Quantity"
                                        value={topForecastProduct?.forecast_quantity || 0}
                                    />
                                    <DrawerMetric
                                        label="Top Seller Forecast Method"
                                        value={topForecastProduct?.selected_model || "-"}
                                    />
                                    <DrawerMetric
                                        label="MAE"
                                        value={topForecastProduct?.mae ?? "-"}
                                    />
                                    <DrawerMetric
                                        label="RMSE"
                                        value={topForecastProduct?.rmse ?? "-"}
                                    />
                                </div>
                            </section>

                            <section className="rounded-3xl bg-[#f8fcff] p-6">
                                <h3 className="text-xl font-extrabold text-[#07102f]">
                                    Forecasting Approach Performance Comparison
                                </h3>

                                <p className="mt-1 text-sm text-[#6f85a3]">
                                    The backend evaluates forecasts generated by Linear Regression and Prophet. The lower RMSE forecasting approach is used for the final forecast.
                                </p>

                                <div className="mt-5 overflow-hidden rounded-2xl border border-blue-100">
                                    <table className="w-full text-left text-sm">
                                        <thead className="bg-[#eef6fb] text-xs uppercase text-[#6f85a3]">
                                            <tr>
                                                <th className="px-4 py-3">Forecasting Approach</th>
                                                <th className="px-4 py-3">Forecast</th>
                                                <th className="px-4 py-3">MAE</th>
                                                <th className="px-4 py-3">RMSE</th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            {(topForecastProduct?.model_comparison || []).map((model) => (
                                                <tr key={model.model} className="border-t bg-white">
                                                    <td className="px-4 py-4 font-bold text-[#17325c]">
                                                        {model.model}
                                                    </td>
                                                    <td className="px-4 py-4">{model.forecast_quantity}</td>
                                                    <td className="px-4 py-4">{model.mae}</td>
                                                    <td className="px-4 py-4 font-bold text-[#1e4db7]">
                                                        {model.rmse}
                                                    </td>
                                                </tr>
                                            ))}

                                            {(!topForecastProduct?.model_comparison ||
                                                topForecastProduct.model_comparison.length === 0) && (
                                                    <tr>
                                                        <td
                                                            colSpan="4"
                                                            className="px-4 py-6 text-center font-semibold text-[#6f85a3]"
                                                        >
                                                            No model comparison available.
                                                        </td>
                                                    </tr>
                                                )}
                                        </tbody>
                                    </table>
                                </div>
                            </section>

                            <section className="rounded-3xl bg-white p-6 shadow-sm">
                                <h3 className="text-xl font-extrabold text-[#07102f]">
                                    Product Forecast Details
                                </h3>

                                <div className="mt-5 overflow-hidden rounded-2xl border border-blue-100">
                                    <table className="w-full text-left text-sm">
                                        <thead className="bg-[#eef6fb] text-xs uppercase text-[#6f85a3]">
                                            <tr>
                                                <th className="px-4 py-3">Product</th>
                                                <th className="px-4 py-3">Sold</th>
                                                <th className="px-4 py-3">Forecast</th>
                                                <th className="px-4 py-3">Selected Forecasting Approach</th>
                                                <th className="px-4 py-3">RMSE</th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            {forecastResults.map((item) => (
                                                <tr key={item.product_id} className="border-t">
                                                    <td className="px-4 py-4 font-bold text-[#17325c]">
                                                        {item.product_name}
                                                    </td>
                                                    <td className="px-4 py-4">{getTotalQuantitySold(item)}</td>
                                                    <td className="px-4 py-4 font-bold text-[#1e4db7]">
                                                        {item.forecast_quantity}
                                                    </td>
                                                    <td className="px-4 py-4 text-xs font-semibold text-[#6f85a3]">
                                                        {item.selected_model
                                                            ? `Selected Forecasting Approach: ${item.selected_model}`
                                                            : "Selected Forecasting Approach: -"}
                                                    </td>
                                                    <td className="px-4 py-4 text-xs font-bold text-[#6f85a3]">
                                                        {item.rmse ?? "-"}
                                                    </td>
                                                </tr>
                                            ))}
                                        </tbody>
                                    </table>
                                </div>
                            </section>
                        </div>
                    </motion.div>
                </div>
            )}

            {showSettings && (
                <SimpleModal title="Settings" onClose={() => setShowSettings(false)}>
                    <p className="text-sm font-semibold text-[#6f85a3]">
                        Settings can be connected later. This page currently focuses on sales forecasting.
                    </p>
                </SimpleModal>
            )}
        </>
    );
}

function HeroMetric({ label, value }) {
    return (
        <div className="rounded-2xl bg-white/12 p-5 backdrop-blur">
            <p className="text-xs font-bold uppercase tracking-widest text-blue-100">
                {label}
            </p>

            <h3 className="mt-3 truncate text-2xl font-extrabold text-white">
                {value}
            </h3>
        </div>
    );
}

function MiniMetric({ label, value }) {
    return (
        <div className="rounded-2xl bg-[#f8fcff] p-4">
            <p className="text-xs font-bold uppercase tracking-widest text-[#6f85a3]">
                {label}
            </p>
            <p className="mt-2 text-xl font-extrabold text-[#1e4db7]">
                {value}
            </p>
        </div>
    );
}

function DrawerMetric({ label, value }) {
    return (
        <div className="rounded-2xl bg-white/10 p-4">
            <p className="text-xs font-bold uppercase tracking-widest text-blue-100">
                {label}
            </p>
            <p className="mt-2 truncate text-xl font-extrabold text-white">
                {value}
            </p>
        </div>
    );
}

function ReportActionButton({ icon: Icon, label, onClick, disabled = false, primary = false }) {
    return (
        <button
            type="button"
            onClick={onClick}
            disabled={disabled}
            className={`inline-flex h-11 items-center justify-center gap-2 rounded-2xl px-4 text-sm font-extrabold shadow-sm transition hover:-translate-y-0.5 hover:shadow-md disabled:cursor-wait disabled:translate-y-0 disabled:bg-gray-200 disabled:text-gray-500 ${
                primary
                    ? "bg-[#0c2f73] text-white hover:bg-[#103986]"
                    : "border border-blue-100 bg-white text-[#17325c] hover:border-[#1e4db7] hover:bg-[#f8fcff] hover:text-[#1e4db7]"
            }`}
        >
            <Icon size={17} />
            {label}
        </button>
    );
}

function buildForecastWorkbookXml({
    forecastResults,
    products,
    inventory,
    generatedDateTime,
    totalForecastQuantity,
    forecastGrowth,
    confidenceScore,
}) {
    const totalProducts = forecastResults.length;
    const totalHistoricalSales = forecastResults.reduce(
        (sum, item) => sum + getTotalSalesRevenue(item),
        0
    );
    const averageForecastQuantity = totalProducts
        ? totalForecastQuantity / totalProducts
        : 0;
    const inventoryRecommendations = buildInventoryRecommendationRows(
        forecastResults,
        products,
        inventory
    );
    const productsRequiringReorder = inventoryRecommendations.filter(
        (item) => item.recommendation !== "Sufficient Stock"
    ).length;
    const methodSummary = buildForecastMethodSummary(forecastResults);

    const forecastResultsRows = [
        headerRow([
            "Product Name",
            "Historical Sales (RM)",
            "Forecast Quantity",
            "Selected Forecast Method",
            "MAE",
            "RMSE",
            "Forecast Growth (%)",
        ]),
        ...forecastResults.map((item) => [
            textCell(item.product_name || "-"),
            numberCell(getTotalSalesRevenue(item), "Currency"),
            numberCell(item.forecast_quantity || 0),
            textCell(item.selected_model || "-"),
            nullableNumberCell(item.mae),
            nullableNumberCell(item.rmse),
            numberCell(getProductForecastGrowth(item) / 100, "Percent"),
        ]),
    ];

    const inventoryRows = [
        headerRow([
            "Product Name",
            "Current Stock",
            "Reorder Level",
            "Forecast Demand",
            "Recommendation",
        ]),
        ...inventoryRecommendations.map((item) => [
            textCell(item.productName),
            numberCell(item.currentStock),
            numberCell(item.reorderLevel),
            numberCell(item.forecastDemand),
            textCell(item.recommendation, getRecommendationStyle(item.recommendation)),
        ]),
    ];

    const historicalSalesRows = [
        [
            textCell("Historical Sales Performance", "Title", {
                mergeAcross: 3,
            }),
        ],
        [
            textCell(
                "Products are ranked by total quantity sold. Total sales revenue is shown for business comparison.",
                "Note",
                { mergeAcross: 3 }
            ),
        ],
        headerRow([
            "Rank",
            "Product Name",
            "Total Quantity Sold",
            "Total Sales Revenue (RM)",
        ]),
        ...[...forecastResults]
            .sort(compareHistoricalSalesPerformance)
            .map((item, index) => [
                numberCell(index + 1),
                textCell(item.product_name || "-"),
                numberCell(getTotalQuantitySold(item)),
                numberCell(getTotalSalesRevenue(item), "Currency"),
            ]),
    ];

    const modelPerformanceRows = [
        headerRow(["Product Name", "Selected Forecast Method", "MAE", "RMSE"]),
        ...forecastResults.map((item) => [
            textCell(item.product_name || "-"),
            textCell(item.selected_model || "-"),
            nullableNumberCell(item.mae),
            nullableNumberCell(item.rmse),
        ]),
    ];

    const summaryRows = [
        [
            textCell("RetailPulse Forecast Report", "Title", {
                mergeAcross: 3,
            }),
        ],
        [textCell("Generated Date and Time", "SummaryLabel"), textCell(generatedDateTime)],
        [textCell("Total Products Analysed", "SummaryLabel"), numberCell(totalProducts)],
        [
            textCell("Total Historical Sales (RM)", "SummaryLabel"),
            numberCell(totalHistoricalSales, "Currency"),
        ],
        [
            textCell("Total Forecast Units", "SummaryLabel"),
            numberCell(totalForecastQuantity),
        ],
        [
            textCell("Average Forecast Quantity", "SummaryLabel"),
            numberCell(averageForecastQuantity),
        ],
        [
            textCell("Products Requiring Reorder", "SummaryLabel"),
            numberCell(productsRequiringReorder),
        ],
        [
            textCell("Most Frequently Selected Method", "SummaryLabel"),
            textCell(methodSummary.bestMethod),
        ],
        [textCell("Method Summary", "SummaryLabel"), textCell(methodSummary.description)],
        [
            textCell("Overall Forecast Growth", "SummaryLabel"),
            numberCell(forecastGrowth / 100, "Percent"),
        ],
        [
            textCell("Forecast Confidence", "SummaryLabel"),
            confidenceScore === null
                ? textCell("-")
                : numberCell(confidenceScore / 100, "Percent"),
        ],
    ];

    const worksheets = [
        buildWorksheet("Executive Summary", summaryRows),
        buildWorksheet("Forecast Results", forecastResultsRows, { freezeHeader: true }),
        buildWorksheet("Inventory Recommendations", inventoryRows, {
            freezeHeader: true,
        }),
        buildWorksheet("Historical Sales Performance", historicalSalesRows, {
            freezeRows: 3,
        }),
        buildWorksheet("Model Performance", modelPerformanceRows, { freezeHeader: true }),
    ];

    return `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">
${buildWorkbookStyles()}
${worksheets.join("\n")}
</Workbook>`;
}

function buildForecastMethodSummary(forecastResults) {
    const counts = forecastResults.reduce(
        (totals, item) => {
            const method = String(item.selected_model || "").toLowerCase();

            if (method.includes("linear")) totals.linearRegression += 1;
            if (method.includes("prophet")) totals.prophet += 1;

            return totals;
        },
        { linearRegression: 0, prophet: 0 }
    );

    let bestMethod = "No Data";

    if (counts.linearRegression > counts.prophet) {
        bestMethod = "Linear Regression";
    } else if (counts.prophet > counts.linearRegression) {
        bestMethod = "Prophet";
    } else if (counts.linearRegression || counts.prophet) {
        bestMethod = "Tie";
    }

    return {
        bestMethod,
        description: `Linear Regression selected for ${counts.linearRegression} product(s); Prophet selected for ${counts.prophet} product(s).`,
    };
}

function buildInventoryRecommendationRows(forecastResults, products, inventory) {
    const productById = new Map(
        products.map((product) => [Number(product.product_id), product])
    );
    const stockByProductId = inventory.reduce((totals, item) => {
        const productId = Number(item.product_id);
        const current = totals.get(productId) || 0;

        totals.set(productId, current + Number(item.quantity_in_stock || 0));
        return totals;
    }, new Map());

    return forecastResults.map((item) => {
        const productId = Number(item.product_id);
        const product = productById.get(productId);
        const currentStock = stockByProductId.get(productId) || 0;
        const reorderLevel = Number(product?.reorder_level ?? item.reorder_level ?? 10);
        const forecastDemand = Number(item.forecast_quantity || 0);
        let recommendation = "Sufficient Stock";

        if (currentStock <= reorderLevel) {
            recommendation = "Urgent Reorder";
        } else if (currentStock <= forecastDemand) {
            recommendation = "Reorder Soon";
        }

        return {
            productName: item.product_name || product?.product_name || "-",
            currentStock,
            reorderLevel,
            forecastDemand,
            recommendation,
        };
    });
}

function getProductForecastGrowth(item) {
    return calculateForecastGrowth(item.forecast_quantity, getTotalQuantitySold(item));
}

function sortForecastResultsByDemand(forecastResults) {
    return [...forecastResults].sort(
        (a, b) => Number(b.forecast_quantity || 0) - Number(a.forecast_quantity || 0)
    );
}

function compareHistoricalSalesPerformance(a, b) {
    const quantityDifference = getTotalQuantitySold(b) - getTotalQuantitySold(a);

    if (quantityDifference !== 0) return quantityDifference;
    return getTotalSalesRevenue(b) - getTotalSalesRevenue(a);
}

function getTotalQuantitySold(item) {
    return Number(item.total_quantity_sold ?? item.total_quantity ?? 0);
}

function getTotalSalesRevenue(item) {
    return Number(item.total_sales_revenue ?? item.total_revenue ?? 0);
}

function calculateForecastGrowth(forecastQuantity, historicalQuantity) {
    const historicalValue = Number(historicalQuantity || 0);

    if (!historicalValue) return 0;
    return ((Number(forecastQuantity || 0) - historicalValue) / historicalValue) * 100;
}

function calculateForecastConfidence(averageRmse, totalForecastQuantity) {
    if (!averageRmse || !totalForecastQuantity) return null;

    const score =
        100 - (Number(averageRmse) / Math.max(Number(totalForecastQuantity), 1)) * 100;
    return Math.max(0, Math.min(100, score));
}

function buildWorksheet(name, rows, options = {}) {
    const columnCount = Math.max(
        ...rows.map((row) =>
            row.reduce((count, cell) => count + 1 + Number(cell.mergeAcross || 0), 0)
        ),
        1
    );
    const widths = getColumnWidths(rows, columnCount);

    return `<Worksheet ss:Name="${xmlEscape(name)}">
<Table>
${widths.map((width) => `<Column ss:AutoFitWidth="0" ss:Width="${width}"/>`).join("\n")}
${rows.map(buildRowXml).join("\n")}
</Table>
${options.freezeHeader || options.freezeRows ? buildFrozenHeaderOptions(options.freezeRows || 1) : ""}
</Worksheet>`;
}

function buildWorkbookStyles() {
    return `<Styles>
<Style ss:ID="Default" ss:Name="Normal">
<Alignment ss:Vertical="Center"/>
<Font ss:FontName="Calibri" ss:Size="11" ss:Color="#17325C"/>
</Style>
<Style ss:ID="Title">
<Alignment ss:Vertical="Center"/>
<Font ss:FontName="Calibri" ss:Size="18" ss:Bold="1" ss:Color="#FFFFFF"/>
<Interior ss:Color="#0C2F73" ss:Pattern="Solid"/>
</Style>
<Style ss:ID="Header">
<Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/>
<Font ss:FontName="Calibri" ss:Size="11" ss:Bold="1" ss:Color="#FFFFFF"/>
<Interior ss:Color="#1E4DB7" ss:Pattern="Solid"/>
<Borders>${buildBorderXml("#B7CBE8")}</Borders>
</Style>
<Style ss:ID="SummaryLabel">
<Font ss:FontName="Calibri" ss:Size="11" ss:Bold="1" ss:Color="#07102F"/>
<Interior ss:Color="#EEF6FB" ss:Pattern="Solid"/>
<Borders>${buildBorderXml("#D9E8F7")}</Borders>
</Style>
<Style ss:ID="Note">
<Alignment ss:Vertical="Center" ss:WrapText="1"/>
<Font ss:FontName="Calibri" ss:Size="11" ss:Italic="1" ss:Color="#475569"/>
<Interior ss:Color="#F8FCFF" ss:Pattern="Solid"/>
<Borders>${buildBorderXml("#D9E8F7")}</Borders>
</Style>
<Style ss:ID="Currency">
<NumberFormat ss:Format="&quot;RM&quot; #,##0.00"/>
<Borders>${buildBorderXml("#E3ECF7")}</Borders>
</Style>
<Style ss:ID="Percent">
<NumberFormat ss:Format="0.0%"/>
<Borders>${buildBorderXml("#E3ECF7")}</Borders>
</Style>
<Style ss:ID="Urgent">
<Font ss:FontName="Calibri" ss:Size="11" ss:Bold="1" ss:Color="#991B1B"/>
<Interior ss:Color="#FEE2E2" ss:Pattern="Solid"/>
<Borders>${buildBorderXml("#FCA5A5")}</Borders>
</Style>
<Style ss:ID="Soon">
<Font ss:FontName="Calibri" ss:Size="11" ss:Bold="1" ss:Color="#9A3412"/>
<Interior ss:Color="#FFEDD5" ss:Pattern="Solid"/>
<Borders>${buildBorderXml("#FDBA74")}</Borders>
</Style>
<Style ss:ID="Sufficient">
<Font ss:FontName="Calibri" ss:Size="11" ss:Bold="1" ss:Color="#166534"/>
<Interior ss:Color="#DCFCE7" ss:Pattern="Solid"/>
<Borders>${buildBorderXml("#86EFAC")}</Borders>
</Style>
<Style ss:ID="Cell">
<Borders>${buildBorderXml("#E3ECF7")}</Borders>
</Style>
</Styles>`;
}

function buildFrozenHeaderOptions(rowCount = 1) {
    return `<WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
<FreezePanes/>
<FrozenNoSplit/>
<SplitHorizontal>${rowCount}</SplitHorizontal>
<TopRowBottomPane>${rowCount}</TopRowBottomPane>
<ActivePane>2</ActivePane>
</WorksheetOptions>`;
}

function buildBorderXml(color) {
    return `<Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="${color}"/>
<Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="${color}"/>
<Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="${color}"/>
<Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="${color}"/>`;
}

function getColumnWidths(rows, columnCount) {
    const widths = Array.from({ length: columnCount }, () => 80);

    rows.forEach((row) => {
        let columnIndex = 0;

        row.forEach((cell) => {
            const span = 1 + Number(cell.mergeAcross || 0);
            const textLength = String(cell.value ?? "").length;
            const calculatedWidth = Math.min(Math.max(textLength * 7 + 20, 80), 260);

            widths[columnIndex] = Math.max(widths[columnIndex], calculatedWidth);
            columnIndex += span;
        });
    });

    return widths.map((width) => Math.round(width));
}

function buildRowXml(row, rowIndex) {
    const height = rowIndex === 0 ? 28 : 22;

    return `<Row ss:Height="${height}">
${row.map(buildCellXml).join("\n")}
</Row>`;
}

function buildCellXml(cell) {
    const attributes = [
        `ss:StyleID="${cell.style || "Cell"}"`,
        cell.mergeAcross ? `ss:MergeAcross="${cell.mergeAcross}"` : "",
    ]
        .filter(Boolean)
        .join(" ");

    return `<Cell ${attributes}><Data ss:Type="${cell.type}">${xmlEscape(
        cell.value
    )}</Data></Cell>`;
}

function headerRow(labels) {
    return labels.map((label) => textCell(label, "Header"));
}

function textCell(value, style = "Cell", options = {}) {
    return {
        type: "String",
        value: value ?? "",
        style,
        ...options,
    };
}

function numberCell(value, style = "Cell") {
    return {
        type: "Number",
        value: Number(value || 0).toFixed(2).replace(/\.00$/, ""),
        style,
    };
}

function nullableNumberCell(value) {
    const numericValue = Number(value);

    if (value === null || value === undefined || Number.isNaN(numericValue)) {
        return textCell("-");
    }

    return numberCell(numericValue);
}

function getRecommendationStyle(recommendation) {
    if (recommendation === "Urgent Reorder") return "Urgent";
    if (recommendation === "Reorder Soon") return "Soon";
    return "Sufficient";
}

function xmlEscape(value) {
    return String(value ?? "")
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&apos;");
}

function SummaryCard({ title, value, icon: Icon, color }) {
    return (
        <div className="rounded-2xl bg-white p-6 shadow-sm">
            <div className="flex items-center justify-between">
                <p className="text-xs font-bold uppercase tracking-widest text-[#6f85a3]">
                    {title}
                </p>

                <div className="grid h-10 w-10 place-items-center rounded-full bg-[#eef6fb]">
                    <Icon size={18} className={color} />
                </div>
            </div>

            <h2 className={`mt-4 truncate text-xl font-extrabold ${color}`}>
                {value}
            </h2>
        </div>
    );
}

function ForecastTable({ title, data, metric = "forecast", tooltip }) {
    return (
        <div className="rounded-2xl bg-white p-6 shadow-sm">
            <div className="mb-5 flex items-center gap-2">
                <h2 className="text-xl font-extrabold text-[#07102f]">{title}</h2>
                {tooltip && <InfoTooltip text={tooltip} ariaLabel={`About ${title}`} />}
            </div>

            <div className="space-y-3">
                {data.map((item) => (
                    <div
                        key={item.product_id}
                        className="flex items-center justify-between rounded-2xl bg-[#f8fcff] p-4"
                    >
                        <div>
                            <p className="font-extrabold text-[#17325c]">{item.product_name}</p>
                            <p className="text-xs font-bold text-[#6f85a3]">
                                {metric === "historicalRevenue"
                                    ? `Revenue: ${formatCurrency(getTotalSalesRevenue(item))}`
                                    : `Sold: ${getTotalQuantitySold(item)} units`}
                            </p>
                        </div>

                        <span className="rounded-full bg-blue-100 px-4 py-2 text-sm font-extrabold text-[#1e4db7]">
                            {metric === "historicalRevenue"
                                ? "Historical"
                                : `Forecast ${item.forecast_quantity}`}
                        </span>
                    </div>
                ))}

                {data.length === 0 && <EmptyBox text="No data found." />}
            </div>
        </div>
    );
}

function InfoTooltip({ text, ariaLabel = "More information" }) {
    const tooltipId = useId();
    const [isOpen, setIsOpen] = useState(false);

    return (
        <span
            className="relative inline-flex"
            onMouseEnter={() => setIsOpen(true)}
            onMouseLeave={() => setIsOpen(false)}
        >
            <button
                type="button"
                aria-label={ariaLabel}
                aria-describedby={isOpen ? tooltipId : undefined}
                title={text}
                onClick={() => setIsOpen(true)}
                onFocus={() => setIsOpen(true)}
                onBlur={() => setIsOpen(false)}
                className="grid h-6 w-6 cursor-help place-items-center rounded-full text-[#6f85a3] transition hover:bg-[#eef6fb] hover:text-[#1e4db7] focus:outline-none focus:ring-2 focus:ring-[#1e4db7]/30"
            >
                <Info size={15} aria-hidden="true" />
            </button>

            <motion.span
                id={tooltipId}
                role="tooltip"
                initial={false}
                animate={{
                    opacity: isOpen ? 1 : 0,
                    y: isOpen ? 0 : -4,
                    visibility: isOpen ? "visible" : "hidden",
                }}
                transition={{ duration: 0.16, ease: "easeOut" }}
                className="pointer-events-none absolute right-0 top-8 z-20 w-72 max-w-[calc(100vw-3rem)] rounded-xl border border-[#d9e7f5] bg-white px-4 py-3 text-left text-xs font-semibold leading-5 text-[#17325c] shadow-xl"
            >
                {text}
            </motion.span>
        </span>
    );
}

function EmptyBox({ text }) {
    return (
        <div className="rounded-xl bg-[#f4fbff] p-5 text-sm font-semibold text-[#6f85a3]">
            {text}
        </div>
    );
}

function SimpleModal({ title, children, onClose }) {
    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 backdrop-blur-sm">
            <div className="w-[480px] rounded-3xl bg-white p-7 shadow-2xl">
                <div className="mb-5 flex items-center justify-between">
                    <h2 className="text-2xl font-extrabold text-[#07102f]">{title}</h2>

                    <button
                        onClick={onClose}
                        className="rounded-full bg-[#eef6fb] px-3 py-1 text-sm font-bold text-[#254e7a]"
                    >
                        ✕
                    </button>
                </div>

                {children}
            </div>
        </div>
    );
}
